"""
responses.py — Static response templates for the chatbot.

Covers all intents in INTENT_MAP. Clear, warm, helpful.
Always ends with a soft CTA. Never reveals signals or market data.
"""
from __future__ import annotations

from core.config import PAYMENT_AMOUNT, SUBSCRIPTION_DAYS, PAYMENT_BANK, PAYMENT_ACCOUNT, PAYMENT_NAME

RESPONSES: dict[str, str] = {

    "greeting": (
        "👋 *Welcome to the Signal System!*\n\n"
        "I'm your assistant — here to help you understand the platform and get started.\n\n"
        "Here's what you can ask me about:\n"
        "📊 *Signals* — how they work\n"
        "💰 *Subscription* — pricing and how to pay\n"
        "🌍 *Markets* — what we cover\n"
        "📈 *Strategy* — our SMC methodology\n"
        "🛡️ *Risk* — how we manage trades\n\n"
        "What would you like to know? 😊"
    ),

    "signals": (
        "📊 *Our Trading Signals*\n\n"
        "Every signal is generated by a strict multi-step SMC engine:\n\n"
        "1️⃣ *H1 Bias* — Trend, premium/discount zones, key levels\n"
        "2️⃣ *Liquidity Sweep* — Visible wick beyond stop clusters\n"
        "3️⃣ *Structure Break* — CHOCH or BOS on M15\n"
        "4️⃣ *POI Return* — Price back in Order Block or FVG\n"
        "5️⃣ *Confirmation* — Strong candle or engulfing\n"
        "6️⃣ *Session* — London or New York only (for Forex)\n\n"
        "If ANY condition fails → no signal is sent.\n\n"
        "Each signal includes: *Entry | Stop Loss | TP1 (1:2) | TP2 (1:3) | Final TP*\n\n"
        "🔒 Signals are sent exclusively to our *private channel*.\n"
        "Type /pay to get access."
    ),

    "subscribe": (
        f"💳 *Subscription Details*\n\n"
        f"📅 Duration: *{SUBSCRIPTION_DAYS} days*\n"
        f"💰 Price: *₦{PAYMENT_AMOUNT:,}*\n\n"
        f"*Payment Method:*\n"
        f"🏦 Bank: *{PAYMENT_BANK}*\n"
        f"📋 Account: `{PAYMENT_ACCOUNT}`\n"
        f"👤 Name: {PAYMENT_NAME}\n\n"
        f"*How to subscribe:*\n"
        f"1️⃣ Make the transfer to the account above\n"
        f"2️⃣ Type /pay in this chat\n"
        f"3️⃣ Send your transaction reference / screenshot\n"
        f"4️⃣ Admin approves and sends your exclusive invite link ✅\n\n"
        f"Questions? Just ask — I'm here to help."
    ),

    "how_it_works": (
        "🤖 *How the System Works*\n\n"
        "Our engine scans Crypto & Forex markets 24/7 using a 14-step filter:\n\n"
        "🔍 *Analysis (H1 timeframe):*\n"
        "• Detects trend structure (HH/HL or LH/LL)\n"
        "• Locates price in premium or discount zones\n"
        "• Confirms price at a key H1 level\n"
        "• Validates liquidity sweep with visible wick\n\n"
        "⚡ *Confirmation (M15 timeframe):*\n"
        "• CHOCH or BOS structure break\n"
        "• Return to Order Block or Fair Value Gap\n"
        "• Strong momentum or engulfing candle\n"
        "• Clear rejection wick\n\n"
        "🚫 *If ANY condition fails → WAIT (no signal)*\n\n"
        "Only clean setups make it through. Quality over quantity.\n\n"
        "Type /pay to subscribe and receive signals live."
    ),

    "strategy": (
        "📐 *Smart Money Concepts (SMC) Strategy*\n\n"
        "We trade the way institutional traders (banks, hedge funds) think:\n\n"
        "🏦 *Smart Money* uses retail stop-losses as entry liquidity.\n"
        "We identify *where* stops are clustered and wait for a sweep.\n\n"
        "Key concepts we use:\n"
        "• *Order Blocks (OB)* — last opposing candle before an impulse\n"
        "• *Fair Value Gaps (FVG)* — price imbalances that get revisited\n"
        "• *CHOCH/BOS* — structure shifts confirming direction change\n"
        "• *Premium/Discount* — only buy cheap, only sell expensive\n"
        "• *Session Filter* — London & NY only (no Asian session noise)\n\n"
        "Minimum 1:2 Risk-to-Reward on every single trade. No exceptions.\n\n"
        "🔒 Type /pay to access live signals."
    ),

    "results": (
        "📈 *System Performance*\n\n"
        "Our system prioritises *quality over quantity*:\n\n"
        "✅ Minimum 1:2 Risk-to-Reward (every trade)\n"
        "✅ All 14 confirmation gates must pass\n"
        "✅ No signals during low-volatility Asian session (Forex)\n"
        "✅ Stop loss placed beyond liquidity sweep wick\n\n"
        "⚠️ *Important disclaimer:*\n"
        "Past results do not guarantee future performance.\n"
        "Trading involves risk. Only trade what you can afford to lose.\n\n"
        "🔒 Subscribe to follow along live → /pay"
    ),

    "markets": (
        "🌍 *Markets We Cover*\n\n"
        "₿ *Crypto (24/7):*\n"
        "• BTCUSDT — Bitcoin\n"
        "• ETHUSDT — Ethereum\n"
        "• SOLUSDT — Solana\n\n"
        "💱 *Forex (London & NY sessions):*\n"
        "• EUR/USD\n"
        "• GBP/USD\n"
        "• USD/JPY\n\n"
        "All signals include full parameters:\n"
        "✅ Entry | 🛑 Stop Loss | 🎯 TP1 | 🎯 TP2 | 🏆 Final TP\n\n"
        "Type /pay to get access."
    ),

    "risk": (
        "🛡️ *Risk Management*\n\n"
        "Every trade we signal follows strict risk rules:\n\n"
        "📍 *Stop Loss* — placed beyond the liquidity sweep wick\n"
        "  (outside where Smart Money entered, not arbitrary)\n\n"
        "🎯 *Take Profit levels:*\n"
        "• TP1 = 1:2 Risk-to-Reward (minimum — always achievable)\n"
        "• TP2 = 1:3 Risk-to-Reward\n"
        "• Final TP = next liquidity pool target\n\n"
        "❌ *No RR < 1:2* — if the setup doesn't offer 1:2, we WAIT.\n\n"
        "⚠️ We signal — you decide position size based on *your* risk tolerance.\n"
        "Never risk more than 1-2% of your account per trade.\n\n"
        "Type /pay to get started."
    ),

    "help": (
        "🆘 *Support*\n\n"
        "Here's how I can help right now:\n\n"
        "• *Subscription questions* → ask about pricing or type /pay\n"
        "• *Payment approved but no invite?* → contact admin directly\n"
        "• *Technical issues?* → describe the problem and I'll guide you\n\n"
        "Common commands:\n"
        "/pay — View payment details & submit proof\n"
        "/start — Restart this bot\n\n"
        "Admin typically responds within a few hours.\n"
        "What's the issue? I'll do my best to help 🙏"
    ),

    "unknown": (
        "🤔 I want to make sure I give you the right answer.\n\n"
        "Here's what I can help with:\n"
        "• How the signal system works\n"
        "• Which markets we cover\n"
        "• Pricing and how to subscribe\n"
        "• Our trading strategy (SMC)\n"
        "• Risk management rules\n\n"
        "What would you like to know more about? 😊"
    ),
}
